name: Deploy com Vite para GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: npm install

      - name: Criar arquivo .env.preview
        run: echo 'VITE_ROUTER_MODE=hash' > .env.preview

      - name: Build com Vite
        env:
          VITE_BASE_BACKEND_URL: ${{ secrets.VITE_BASE_BACKEND_URL }}
        run: npm run build:preview

      - name: Deploy para GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: dist
